![](http://sigdelta.com/assets/images/sages-sd-logo.png)

# Analiza danych i uczenie maszynowe w Python

Autor notebooka: Jakub Nowacki.

## NumPy

[NumPy](http://www.numpy.org/) jest podstawowym pakie (dodatkowym) w Pythonie do obliczeń naukowych. Integruje on niskopoziomowe biblioteki takie jak BLAS i LAPACK lub ATLAS. Podstawowe właściwości NumPy to :
* potężny N-wymiarowy obiekt tablicy danych
* rozbudowane funkcje (
* narzędzia do integracji z codem napisanym w C/C++ i Fortranie
* narzędzia do algebry liniowej, transformaty Fouriera czy generator liczb losowych

Numpy importujemy używając nazwy `numpy`, najlepiej w całości jako pakiet. Często stosowany jest alias `np`.

In [1]:
import numpy as np

## Tablica

Podstawowym obiektem w Numpy jest tablica zwana `ndarray` od ang. *N-dimensional array*. Talbicę można stworzyć z kolekcji za pomocą funkcji `ndarray` lub jej aliasu `array`:

In [3]:
n1 = np.array([1,2,3])
print(n1)
n2 = np.array([[1,2],[3,4]])
n2
# ... itd

[1 2 3]


array([[1, 2],
       [3, 4]])

Każda komenda ma poniższe właściwości:

In [4]:
print('Wymiar: n1: {}, n2: {}'.format(n1.ndim, n2.ndim))
print('Kształt: n1: {}, n2: {}'.format(n1.shape, n2.shape))
print('Rozmiar: n1: {}, n2: {}'.format(n1.size, n2.size))
print('Typ: n1: {}, n2: {}'.format(n1.dtype, n2.dtype))
print('Rozmiar elementu (w bajtach): n1: {}, n2: {}'.format(n1.itemsize, n2.itemsize))
print('Wskaźnik do danych: n1: {}, n2: {}'.format(n1.data, n2.data))

Wymiar: n1: 1, n2: 2
Kształt: n1: (3,), n2: (2, 2)
Rozmiar: n1: 3, n2: 4
Typ: n1: int32, n2: int32
Rozmiar elementu (w bajtach): n1: 4, n2: 4
Wskaźnik do danych: n1: <memory at 0x00000284B46B1B88>, n2: <memory at 0x00000284B46D8990>


W przeciwieństwie do kolekcji, tablice mogą mieć tylko jeden typ elementu, choć moze być złożony; zobacz [ten link](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

In [5]:
for v in [1, 1., 1j]:
    a = np.array([v])
    print('Tablica: {}, typ: {}'.format(a, a.dtype))
# Można też wymusić typ przy tworzeniu tablicy
a = np.array([1], dtype=str)
print('Tablica: {}, typ: {}'.format(a, a.dtype))

Tablica: [1], typ: int32
Tablica: [1.], typ: float64
Tablica: [0.+1.j], typ: complex128
Tablica: ['1'], typ: <U1


Są też ogólne metody tworzenia tablic o specyficznych właściwościach:

In [8]:
print('Zakres:\n{}'.format(np.arange(1,10)))
print('Zera:\n{}'.format(np.zeros((2,3))))
print('Jedynki:\n{}'.format(np.ones((3,2))))
print('Pusta:\n{}'.format(np.empty((2,7)))) # Bez inicjalizacji
print('Pusta:\n{}'.format(np.empty((2,7),dtype=str))) # Bez inicjalizacji
#format(a, a.dtype)
print('Losowa:\n{}'.format(np.random.rand(2,2)))

Zakres:
[1 2 3 4 5 6 7 8 9]
Zera:
[[0. 0. 0.]
 [0. 0. 0.]]
Jedynki:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Pusta:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Pusta:
[['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']]
Losowa:
[[0.09443156 0.55874832]
 [0.69020562 0.04296123]]


Pobieranie wartości z tablic:

In [9]:
# Jak w kolekcjach
print(n1[1], n2[1][1])
# ... ale jest też skrót
print(n2[1,1])
# Przecięcia podobnie w kolekcjach
print(n2[1,:])
print(n2[:,1])
print(n2[1,:1])
print(n2[1,1:2])

2 4
4
[3 4]
[2 4]
[3]


Operacje w tablicach wykonywane są na poszczególnych elementach, np. jak pomnożymy dwie tablice pomnożone zostaną tylko elementy na tych samych pozycjach przez siebie.

In [10]:
a = np.random.randint(100,size=(2,3))
print('a = \n{}'.format(a))
print('2*a = \n{}'.format(2*a))
print('a**2 = \n{}'.format(a**2))
print('a*a = \n{}'.format(a*a))
#a.dot(aa) - mnozenie macierzowe tablic

a = 
[[89 34 14]
 [86 89  0]]
2*a = 
[[178  68  28]
 [172 178   0]]
a**2 = 
[[7921 1156  196]
 [7396 7921    0]]
a*a = 
[[7921 1156  196]
 [7396 7921    0]]


## Macierze

Numpy ma również typ macierzy `matrix`. Jest on bardzo podobny do tablicy ale podstawowe operacje wykonywane są w sposób macierzowy a nie tablicowy.

In [11]:
m = np.matrix([[1,2], [3,4]])
mm = np.matrix([[5,6], [7,8]])

print('m*mm = \n{}'.format(m*mm))
print('m**2 = \n {}'.format(m**2))
print('m*2 = \n ={}'.format(m*2))

d = np.diag([3,4])
print('d = \n {}'.format(d))
print('d*m = \n {}'.format(d*m))

#m.t - transpozycja

m*mm = 
[[19 22]
 [43 50]]
m**2 = 
 [[ 7 10]
 [15 22]]
m*2 = 
 =[[2 4]
 [6 8]]
d = 
 [[3 0]
 [0 4]]
d*m = 
 [[ 3  6]
 [12 16]]


Niemniej, tablice można używać podobnie, ale do mnożenia trzeba wykorzystywać funkcje `dot`:

In [ ]:
a = np.array([[1,2], [3,4]])
aa = np.array([[5,6], [7,8]])

print('a*aa = \n{}'.format(a*aa))
print('a.dot(aa) = \n{}'.format(a.dot(aa)))
print('a**2 = \n {}'.format(a**2))
print('a*2 = \n ={}'.format(a*2))

Dodatkowo, operacje algebry liniowej można wykonywać zarówno na tablicach jak i macierzach, np:

In [ ]:
print('det(m) = {}'.format(np.linalg.det(m)))
print('det(a) = {}'.format(np.linalg.det(a)))

## Zadanie
Mamy liczbę trzycyfrową. Jeżeli od liczny dziesiątek odejmiemy liczbę jedności otrzymamy 6. Jeżeli do liczby dziesiątek dodamy liczbę jedności otrzymamy 10.

* znajdź wszystkie liczby trzycyfrowe spełniające ten warunek
* znajdź liczby trzycyfrowe podzielne przez 3

[Podpowiedź](https://pl.wikipedia.org/wiki/Uk%C5%82ad_r%C3%B3wna%C5%84_liniowych):
$$ Ax=B $$
$$ x = A^{-1}B $$

In [28]:
A= np.matrix([[1,-1], [1,1]])
B=np.matrix([[6], [10]])
x=A**(-1)*B
r1=np.arange(1,10)*100+x[0]*10+x[1]
print(r1)
#np.arange(1,10,2) - co 2
#% - modulo
#r1%3
#r1[r1%3==0]
#np.argwhere(r1%3==0) # 



[[182. 282. 382. 482. 582. 682. 782. 882. 982.]]
